package dev.iiahmed.disguise;

public enum DisguiseResponse {

    FAIL_VERSION_NOT_SUPPORTED,
    FAIL_PLUGIN_NOT_INITIALIZED,
    FAIL_NAME_ALREADY_ONLINE,
    FAIL_ALREADY_DISGUISED,
    FAIL_NAME_CHANGE_EXCEPTION,
    SUCCESS

}
